# .zshrc by Jordan Lewis, stolen by Paul Kernfeld

# Environment variables {{{
HISTFILE=~/.zshhistory            # What histfile are we using?
HISTSIZE=100000                   # Big = better
SAVEHIST=7000                     # When to save to the file?
TERM=xterm-256color
export SHELL=`which zsh`                 # New shells don't open bash
export EDITOR=vim                        # vim now
export GREP_OPTIONS='--color=auto'       # Color my greps
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>' # This is used for navigating forward and backward

if [ $(uname) = Linux ]; then 
    alias ls='ls --color=auto'
else
    export CLICOLOR=1
fi

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home

# Put brew python first
export PATH="/usr/local/bin:$PATH"
# }}}

# Setopts {{{
setopt auto_cd             # If I type a directory, assume I mean to cd to it
setopt auto_pushd          # Automatically push directories onto the stack
setopt badpattern          # Print an error message on badly formed glob
#setopt cdablevars          # So we can cd to metachars like ~
setopt correct             # Attempt typo corrections
setopt complete_in_word    # 
#setopt extended_glob       # Allow ~ # ^ metachars in globbing
# disabled - this makes it so you can't use the ^ revision spec thing with git!
setopt extended_history    # More information in history
setopt hist_ignore_space   # Don't put space-prepended commands in the history
setopt interactivecomments # Allow comments even in the interactive shell
setopt listpacked          # Menucomplete can use different col widths
setopt magicequalsubst     # echo foo=~/bar -> foo/home/jlewis/bar
#setopt markdirs            # Append / to all glob-completed dirs
# disabled - given a dirtree foo/bar/baz.txt, cp -R foo/* /tmp/ causes baz.txt
# to be sent to /tmp/. no good!
setopt multios             # Allow multiple redirection!
setopt nobeep              # Don't beep
setopt no_flowcontrol      # No stupid flow control!
setopt nullglob            # Delete a glob if it doesn't match anything
setopt promptsubst
setopt pushd_ignore_dups   # Don't push multiple copies of a directory
# }}}

# Autoloads {{{
autoload -U compinit; compinit
autoload -U predict-on
autoload -U edit-command-line
autoload -U copy-earlier-word
autoload -U add-zsh-hook
# }}}

# Sometimes I like to open a lot of files, okay?
ulimit -n 2000

# Zle {{{
zle -N predict-on;
zle -N predict-off;
zle -N edit-command-line
zle -N copy-earlier-word
# }}}

# Zstyles {{{
zstyle ':completion::complete:*' use-cache 1 # uses completion cache
zstyle ':completion::complete:*' cache-path ~/.zshcache
zstyle ':completion:*' menu select # menu-style completion
zstyle ':completion:*:functions' ignored-patterns '_*' # no missing completions
# }}}

# Keybindings {{{
bindkey -e
# }}}

# Aliases {{{
# Misc {{{
alias cp='nocorrect cp'        # Don't correct this cmd
alias mkdir='nocorrect mkdir'  # Don't correct this cmd
alias mv='nocorrect mv'        # Don't correct this cmd
alias touch='nocorrect touch'  # Don't correct this cmd
alias sl='sl -l'               # ... dumb
alias termcast='telnet 213.184.131.118 37331'   # noway.ratry.ru 37331
alias slurp='wget -r --no-parent'
alias deflac='for file in *.flac; do $(flac -cd "$file" | lame -V 0 --vbr-new - "${file%.flac}.mp3"); done'   # convert all flacs in directory to v0

# Make a pseudorandom password. Usage: pwgen {length}
pwgen() {
  python -c 'import random; import string; print "".join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range('$*'))'
}

# add git-number support if it exists
which git-number &> /dev/null
if [ $? -eq 0 ]; then
    numbercommands=(add rm diff reset checkout co)
    git()
    {
        if [ $1 = "status" ]; then
            /usr/local/bin/git number;
        elif [ ${numbercommands[(r)$1]} ]; then
            /usr/local/bin/git number "$@"
        else
            /usr/local/bin/git "$@"
        fi
    }
else
    alias git='nocorrect git'
fi
# }}}
# Shortcuts {{{
alias '..'='cd ..'               # cd .. takes too much effort!
alias 'web'='python -m SimpleHTTPServer' # hosts . on :8000
alias hide='xset dpms force standby; exit' # kills my LCD monitor
alias reload='source ~/.zshrc'   # re-sources this
alias prettyjson='python -c "import sys, json; print json.dumps(json.load(sys.stdin), sort_keys=True, indent=4)"'
alias ec='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n $@'
# }}}
# Git {{{
alias g='git'
alias gs='git status'
alias gd='git diff'
alias gf='git fetch'
alias ga='git add'
alias gl='git log'
git-grep-all () { git grep $1 $(git rev-list --all) }
# }}}
# Global shortcuts {{{
alias -g ...='../..'             # Ease of going backward
alias -g ....='../../..'         # Yes
alias -g .....='../../../..'     # YES
alias -g G='|egrep'              # cat biglongfile G cheese
alias -g H='|head'               # cat biglongfile H
alias -g L='|less'               # cat biglongfile L
alias -g T='|tail'               # cat biglongfile T
alias -g W='|wc'                 # cat biglongfile W
# }}}
# }}}

# Prompt {{{
source ~/.zshprompt
# }}}

# Stuff that's specific to one computer {{{
source ~/.zsh_specific
# }}}
